### ISSUE TITLE
Not able to get "status" : "200 OK" for Bulk Load API Call

### ISSUE THREAD

**Issue by mansimht** [aws-samples/amazon-neptune-samples#118]
I am not able to do Neptune bulk load from AWS S3 using curl command Bulk Load API Call ?
Command:
curl -X POST \
    -H 'Content-Type: application/json' \
    https://*******.cluster-c4brigvg3m9m.us-east-2.neptune.amazonaws.com:8182/loader -d'
    { 
      "source" : "s3://******/Unsaved/2022/12/13/4a873928-9910-47b0-85ca-de593ace4f4a.csv", 
      "format" : "csv",  
      "iamRoleArn" : "arn:aws:iam::959061167427:role/NeptuneLoadFroms3", 
      "region" : "us-east-2", 
      "failOnError" : "FALSE",
    }'

This is the error I am getting:
{"code":"AccessDeniedException","requestId":"f6243cd3-2a4f-48a2-9d91-13803c199ef1","detailedMessage":"Missing Authentication Token"}

Can you please help me why I am getting this error  and How can I resolve it ?

**Comment by triggan** [comment]
Hi - Is this related to any of the packages hosted in this repo?  If not, can you please move this question to StackOverflow, re:Post, or open an AWS Support case?

**Comment by triggan** [comment]
Answered here:  https://repost.aws/questions/QUsN2qlGBqR8SN76lPU10Ssg/not-able-to-get-status-200-ok-for-bulk-load-api-call-using-aws-neptune

Please do not post support-related questions as issues to this repository.  This should only be used for issues against the open sourced utilities managed here.
