### ISSUE TITLE
Not able to load data using neptune bulk load

### ISSUE THREAD

**Issue by mansimht** [aws-samples/amazon-neptune-samples#119]
Submit api call get initiate successfully with status 200 ok. 
But when able to check Monitor the Loading Process using this command then I am able to get this error. 
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://*****:8182/loader/33aaf4f9-54b5-4f7b-8b39-b00cfb379397

**Comment by triggan** [comment]
Answered here: https://repost.aws/questions/QUgGTMmr1KR1y3o0e-DApEMg/not-able-to-load-data-using-neptune-bulk-load-credential-should-be-scoped-to-a-valid-region-not-us-east-1-error-shows

Please do not post support-related questions as issues to this repository.  This should only be used for issues against the open sourced utilities managed here.
