### ISSUE TITLE
AWS Neptune - Submit Query with empty string crashes

### ISSUE THREAD

**Issue by Akshay-15mca1098** [aws-samples/amazon-neptune-samples#2]
Script with `" "` (empty space with space) works fine but `""` empty string crashes.

    gremlin> g.addV("Test").property("title", "Test node 1").property("a", "")
    {"requestId":"111xxxx-xxx-xxx-xxx-xxx","code":"MalformedQueryException","detailedMessage":"Query parsing failed at line 1, character position at 62, error message : no viable alternative at input 'g.addV(\"Test\").property(\"title\",\"Test node 1\").property(\"a\",\"\"'"}
    Type ':help' or ':h' for help.
    Display stack trace? [yN]
    
    
    gremlin> g.addV("Test").property("title", "Test node 1").property("a", " ")
    ==>v[98b22f0f-6be0-fb11-38cc-066bf7e17051]

---------------

This works fine with NEO4J Gremlin, so I doubt this is a Gremlin issue. Is this a Neptune bug or feature?

**Comment by beebs-systap** [comment]
Is this on the Neptune preview or the GA?
