### ISSUE TITLE
sdk reference in cloudFormation template not available anymore

### ISSUE THREAD

**Issue by cyrilou242** [aws-samples/amazon-neptune-samples#30]
Hello, 

I was trying to plug a notebook to an existing neptune instance, following the [Analyze Amazon Neptune Graphs using Amazon SageMaker Jupyter Notebooks](https://aws.amazon.com/fr/blogs/database/analyze-amazon-neptune-graphs-using-amazon-sagemaker-jupyter-notebooks/) tutorial. (the part "What if I want to reuse an existing Neptune cluster with SageMaker?")

The cloudFormation template is referencing an eclipse rdf4j sdk version that is not available anymore, resulting in the stack failing when trying to download it.

https://github.com/aws-samples/amazon-neptune-samples/blob/356cfc89434fc6b6d5015ab6a57c0678d0094c05/neptune-sagemaker/cloudformation-templates/neptune-sagemaker/neptune-sagemaker-nested-stack.json#L254

I used version [2.4.6](https://ftp.osuosl.org/pub/eclipse/rdf4j/eclipse-rdf4j-2.4.6-sdk.zip) instead and everything went fine, but you may want to consider 2.5.x or 3.x versions. 

Thanks for the great tutorial.

**Comment by iansrobinson** [comment]
Hi @cyrilou242 

Thank you for reporting this. I've updated the RDF4J and Gremlin Console references to align with the versions in the Neptune Quick Start CloudFormation templates (2.5.4 and 3.4.1 respectively).

ian
