### ISSUE TITLE
Noticed two Parameters Keys

### ISSUE THREAD

**Issue by slowshi** [aws-samples/amazon-neptune-samples#59]
Hey, I'm working on enabling streams in my Neptune template and checked here for an example of how to implement it. I noticed in the json that there are two parameters keys (lines 110 and 115), which seems like a mistake.

Reference:
https://github.com/aws-samples/amazon-neptune-samples/blob/a33f481707014025b41857966144b4a59d6c553b/gremlin/neptune-streams/cloudformation-templates/services-neptune-stack.json#L100-L125

**Comment by iansrobinson** [comment]
Thanks for reporting this. The first Parameters should probably be folded into the second: I'll look to push a change.

Regarding the actual enabling of Streams, the template uses the lab mode format for enabling streams – see https://docs.aws.amazon.com/neptune/latest/userguide/features-lab-mode.html.

This, while still currently supported, has been replaced by a `neptune_streams` parameter: https://docs.aws.amazon.com/neptune/latest/userguide/features-lab-mode.html

The CloudFormation template will work as is for enabling Streams, but the preferred approach now would be:

```
 "Parameters": { 
       " neptune_streams": "1" 
     }
```
